version: 2

project_name: airtruct

before:
  hooks:
    - go mod tidy

builds:
  - id: linux-amd64
    binary: airtruct
    main: ./cmd/airtruct
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w

  - id: linux-arm64
    binary: airtruct
    main: ./cmd/airtruct
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w

  - id: darwin-amd64
    binary: airtruct
    main: ./cmd/airtruct
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w

  - id: darwin-arm64
    binary: airtruct
    main: ./cmd/airtruct
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w

  - id: windows-amd64
    binary: airtruct
    main: ./cmd/airtruct
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w

  - id: windows-arm64
    binary: airtruct
    main: ./cmd/airtruct
    env:
      - CGO_ENABLED=1
      - CC=aarch64-w64-mingw32-gcc
      - CXX=aarch64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - arm64
    ldflags:
      - -s -w

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

dockers:
  - image_templates:
      - "ghcr.io/sananguliyev/airtruct:{{ .Version }}"
      - "ghcr.io/sananguliyev/airtruct:latest"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"

  - image_templates:
      - "ghcr.io/sananguliyev/airtruct:{{ .Version }}-arm64"
      - "ghcr.io/sananguliyev/airtruct:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/sananguliyev/airtruct:{{ .Version }}"
    image_templates:
      - "ghcr.io/sananguliyev/airtruct:{{ .Version }}"
      - "ghcr.io/sananguliyev/airtruct:{{ .Version }}-arm64"

  - name_template: "ghcr.io/sananguliyev/airtruct:latest"
    image_templates:
      - "ghcr.io/sananguliyev/airtruct:latest"
      - "ghcr.io/sananguliyev/airtruct:latest-arm64"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
