version: 2
builds:
  - id: airtruct
    main: ./cmd/airtruct
    binary: airtruct
    goos: [windows, darwin, linux]
    goarch: [amd64, arm64, arm]
    goarm: ["7"]
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
    env:
      - CGO_ENABLED=0
    ldflags: >
      -s -w
      -X main.Version={{.Version}}
      -X main.DateBuilt={{.Date}}
archives:
  - id: airtruct
    ids: [airtruct]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE
dist: target/dist
release:
  github:
    owner: sananguliyev
    name: airtruct
  prerelease: auto
  disable: false
