version: 2
builds:
  - id: airtruct
    main: cmd/airtruct/main.go
    binary: airtruct
    goos: [ windows, darwin, linux, freebsd, openbsd ]
    goarch: [ amd64, arm, arm64 ]
    goarm: [ 6, 7 ]
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
    env:
      - CGO_ENABLED=0
    ldflags: >
      -s -w
      -X github.com/sananguliyev/airtruct/internal/cli.Version={{.Version}}
      -X github.com/sananguliyev/airtruct/internal/cli.DateBuilt={{.Date}}
      -X main.Version={{.Version}}
      -X main.DateBuilt={{.Date}}
archives:
  - id: airtruct
    builds: [ airtruct ]
    format: tar.gz
    files:
      - README.md
      - LICENSE
dist: target/dist
release:
  github:
    owner: sananguliyev
    name: airtruct
  prerelease: auto
  disable: false