// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: common.proto

package protogen

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerStreamStatus int32

const (
	WorkerStreamStatus_waiting   WorkerStreamStatus = 0
	WorkerStreamStatus_running   WorkerStreamStatus = 1
	WorkerStreamStatus_stopped   WorkerStreamStatus = 2
	WorkerStreamStatus_completed WorkerStreamStatus = 3
	WorkerStreamStatus_failed    WorkerStreamStatus = 4
)

// Enum value maps for WorkerStreamStatus.
var (
	WorkerStreamStatus_name = map[int32]string{
		0: "waiting",
		1: "running",
		2: "stopped",
		3: "completed",
		4: "failed",
	}
	WorkerStreamStatus_value = map[string]int32{
		"waiting":   0,
		"running":   1,
		"stopped":   2,
		"completed": 3,
		"failed":    4,
	}
)

func (x WorkerStreamStatus) Enum() *WorkerStreamStatus {
	p := new(WorkerStreamStatus)
	*p = x
	return p
}

func (x WorkerStreamStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerStreamStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (WorkerStreamStatus) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x WorkerStreamStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerStreamStatus.Descriptor instead.
func (WorkerStreamStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *CommonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Stream struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId        *int64                 `protobuf:"varint,2,opt,name=parent_id,proto3,oneof" json:"parent_id,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	InputConfig     string                 `protobuf:"bytes,4,opt,name=input_config,proto3" json:"input_config,omitempty"`
	InputLabel      string                 `protobuf:"bytes,5,opt,name=input_label,proto3" json:"input_label,omitempty"`
	InputComponent  string                 `protobuf:"bytes,6,opt,name=input_component,proto3" json:"input_component,omitempty"`
	OutputConfig    string                 `protobuf:"bytes,7,opt,name=output_config,proto3" json:"output_config,omitempty"`
	OutputLabel     string                 `protobuf:"bytes,8,opt,name=output_label,proto3" json:"output_label,omitempty"`
	OutputComponent string                 `protobuf:"bytes,9,opt,name=output_component,proto3" json:"output_component,omitempty"`
	IsCurrent       bool                   `protobuf:"varint,10,opt,name=is_current,proto3" json:"is_current,omitempty"`
	Status          string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,proto3,oneof" json:"updated_at,omitempty"`
	Processors      []*Stream_Processor    `protobuf:"bytes,14,rep,name=processors,proto3" json:"processors,omitempty"`
	IsHttpServer    bool                   `protobuf:"varint,15,opt,name=is_http_server,proto3" json:"is_http_server,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Stream) Reset() {
	*x = Stream{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stream) ProtoMessage() {}

func (x *Stream) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stream.ProtoReflect.Descriptor instead.
func (*Stream) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *Stream) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Stream) GetParentId() int64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *Stream) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stream) GetInputConfig() string {
	if x != nil {
		return x.InputConfig
	}
	return ""
}

func (x *Stream) GetInputLabel() string {
	if x != nil {
		return x.InputLabel
	}
	return ""
}

func (x *Stream) GetInputComponent() string {
	if x != nil {
		return x.InputComponent
	}
	return ""
}

func (x *Stream) GetOutputConfig() string {
	if x != nil {
		return x.OutputConfig
	}
	return ""
}

func (x *Stream) GetOutputLabel() string {
	if x != nil {
		return x.OutputLabel
	}
	return ""
}

func (x *Stream) GetOutputComponent() string {
	if x != nil {
		return x.OutputComponent
	}
	return ""
}

func (x *Stream) GetIsCurrent() bool {
	if x != nil {
		return x.IsCurrent
	}
	return false
}

func (x *Stream) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Stream) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Stream) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Stream) GetProcessors() []*Stream_Processor {
	if x != nil {
		return x.Processors
	}
	return nil
}

func (x *Stream) GetIsHttpServer() bool {
	if x != nil {
		return x.IsHttpServer
	}
	return false
}

type Stream_Processor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Component     string                 `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`
	Config        string                 `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stream_Processor) Reset() {
	*x = Stream_Processor{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stream_Processor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stream_Processor) ProtoMessage() {}

func (x *Stream_Processor) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stream_Processor.ProtoReflect.Descriptor instead.
func (*Stream_Processor) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Stream_Processor) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Stream_Processor) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *Stream_Processor) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

var file_common_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51234,
		Name:          "protorender.string_value",
		Tag:           "bytes,51234,opt,name=string_value",
		Filename:      "common.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional string string_value = 51234;
	E_StringValue = &file_common_proto_extTypes[0]
)

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\vprotorender\x1a google/protobuf/descriptor.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"*\n" +
	"\x0eCommonResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xd6\x06\n" +
	"\x06Stream\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\tparent_id\x18\x02 \x01(\x03H\x00R\tparent_id\x88\x01\x01\x12\x1d\n" +
	"\x04name\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dR\x04name\x12\"\n" +
	"\finput_config\x18\x04 \x01(\tR\finput_config\x12>\n" +
	"\vinput_label\x18\x05 \x01(\tB\x1c\xfaB\x19r\x17\x10\x01\x18d2\x11^[a-zA-Z0-9 _-]+$R\vinput_label\x12(\n" +
	"\x0finput_component\x18\x06 \x01(\tR\x0finput_component\x12$\n" +
	"\routput_config\x18\a \x01(\tR\routput_config\x12@\n" +
	"\foutput_label\x18\b \x01(\tB\x1c\xfaB\x19r\x17\x10\x01\x18d2\x11^[a-zA-Z0-9 _-]+$R\foutput_label\x12*\n" +
	"\x10output_component\x18\t \x01(\tR\x10output_component\x12\x1e\n" +
	"\n" +
	"is_current\x18\n" +
	" \x01(\bR\n" +
	"is_current\x12@\n" +
	"\x06status\x18\v \x01(\tB(\xfaB%r#R\x06activeR\tcompletedR\x06pausedR\x06failedR\x06status\x12:\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"created_at\x12?\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampH\x01R\n" +
	"updated_at\x88\x01\x01\x12=\n" +
	"\n" +
	"processors\x18\x0e \x03(\v2\x1d.protorender.Stream.ProcessorR\n" +
	"processors\x12&\n" +
	"\x0eis_http_server\x18\x0f \x01(\bR\x0eis_http_server\x1au\n" +
	"\tProcessor\x122\n" +
	"\x05label\x18\x01 \x01(\tB\x1c\xfaB\x19r\x17\x10\x01\x18d2\x11^[a-zA-Z0-9 _-]+$R\x05label\x12\x1c\n" +
	"\tcomponent\x18\x02 \x01(\tR\tcomponent\x12\x16\n" +
	"\x06config\x18\x03 \x01(\tR\x06configB\f\n" +
	"\n" +
	"_parent_idB\r\n" +
	"\v_updated_at*\x98\x01\n" +
	"\x12WorkerStreamStatus\x12\x18\n" +
	"\awaiting\x10\x00\x1a\v\x92\x82\x19\awaiting\x12\x18\n" +
	"\arunning\x10\x01\x1a\v\x92\x82\x19\arunning\x12\x18\n" +
	"\astopped\x10\x02\x1a\v\x92\x82\x19\astopped\x12\x1c\n" +
	"\tcompleted\x10\x03\x1a\r\x92\x82\x19\tcompleted\x12\x16\n" +
	"\x06failed\x10\x04\x1a\n" +
	"\x92\x82\x19\x06failed:F\n" +
	"\fstring_value\x12!.google.protobuf.EnumValueOptions\x18\xa2\x90\x03 \x01(\tR\vstringValueB4Z2github.com/sananguliyev/airtruct/internal/protogenb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_proto_goTypes = []any{
	(WorkerStreamStatus)(0),               // 0: protorender.WorkerStreamStatus
	(*CommonResponse)(nil),                // 1: protorender.CommonResponse
	(*Stream)(nil),                        // 2: protorender.Stream
	(*Stream_Processor)(nil),              // 3: protorender.Stream.Processor
	(*timestamppb.Timestamp)(nil),         // 4: google.protobuf.Timestamp
	(*descriptorpb.EnumValueOptions)(nil), // 5: google.protobuf.EnumValueOptions
}
var file_common_proto_depIdxs = []int32{
	4, // 0: protorender.Stream.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: protorender.Stream.updated_at:type_name -> google.protobuf.Timestamp
	3, // 2: protorender.Stream.processors:type_name -> protorender.Stream.Processor
	5, // 3: protorender.string_value:extendee -> google.protobuf.EnumValueOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	3, // [3:4] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
		ExtensionInfos:    file_common_proto_extTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
