// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: coordinator.proto

package protogen

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterWorkerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterWorkerRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type DeregisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterWorkerRequest) Reset() {
	*x = DeregisterWorkerRequest{}
	mi := &file_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterWorkerRequest) ProtoMessage() {}

func (x *DeregisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*DeregisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *DeregisterWorkerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WorkerStreamStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkerStreamId int64                  `protobuf:"varint,1,opt,name=worker_stream_id,json=workerStreamId,proto3" json:"worker_stream_id,omitempty"`
	Status         WorkerStreamStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=protorender.WorkerStreamStatus" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkerStreamStatusRequest) Reset() {
	*x = WorkerStreamStatusRequest{}
	mi := &file_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStreamStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStreamStatusRequest) ProtoMessage() {}

func (x *WorkerStreamStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStreamStatusRequest.ProtoReflect.Descriptor instead.
func (*WorkerStreamStatusRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerStreamStatusRequest) GetWorkerStreamId() int64 {
	if x != nil {
		return x.WorkerStreamId
	}
	return 0
}

func (x *WorkerStreamStatusRequest) GetStatus() WorkerStreamStatus {
	if x != nil {
		return x.Status
	}
	return WorkerStreamStatus_waiting
}

type ListComponentConfigsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ComponentConfig     `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListComponentConfigsResponse) Reset() {
	*x = ListComponentConfigsResponse{}
	mi := &file_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListComponentConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListComponentConfigsResponse) ProtoMessage() {}

func (x *ListComponentConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListComponentConfigsResponse.ProtoReflect.Descriptor instead.
func (*ListComponentConfigsResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *ListComponentConfigsResponse) GetData() []*ComponentConfig {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetComponentConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetComponentConfigRequest) Reset() {
	*x = GetComponentConfigRequest{}
	mi := &file_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetComponentConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetComponentConfigRequest) ProtoMessage() {}

func (x *GetComponentConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetComponentConfigRequest.ProtoReflect.Descriptor instead.
func (*GetComponentConfigRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *GetComponentConfigRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListWorkersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersRequest) Reset() {
	*x = ListWorkersRequest{}
	mi := &file_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersRequest) ProtoMessage() {}

func (x *ListWorkersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersRequest.ProtoReflect.Descriptor instead.
func (*ListWorkersRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *ListWorkersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListWorkersResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Data          []*ListWorkersResponse_Worker `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersResponse) Reset() {
	*x = ListWorkersResponse{}
	mi := &file_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersResponse) ProtoMessage() {}

func (x *ListWorkersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersResponse.ProtoReflect.Descriptor instead.
func (*ListWorkersResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *ListWorkersResponse) GetData() []*ListWorkersResponse_Worker {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListStreamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStreamsRequest) Reset() {
	*x = ListStreamsRequest{}
	mi := &file_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStreamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStreamsRequest) ProtoMessage() {}

func (x *ListStreamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStreamsRequest.ProtoReflect.Descriptor instead.
func (*ListStreamsRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *ListStreamsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListStreamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Stream              `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStreamsResponse) Reset() {
	*x = ListStreamsResponse{}
	mi := &file_coordinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStreamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStreamsResponse) ProtoMessage() {}

func (x *ListStreamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStreamsResponse.ProtoReflect.Descriptor instead.
func (*ListStreamsResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{8}
}

func (x *ListStreamsResponse) GetData() []*Stream {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamRequest) Reset() {
	*x = GetStreamRequest{}
	mi := &file_coordinator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamRequest) ProtoMessage() {}

func (x *GetStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamRequest.ProtoReflect.Descriptor instead.
func (*GetStreamRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{9}
}

func (x *GetStreamRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Event struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkerStreamId int64                  `protobuf:"varint,1,opt,name=worker_stream_id,json=workerStreamId,proto3" json:"worker_stream_id,omitempty"`
	Section        string                 `protobuf:"bytes,2,opt,name=section,proto3" json:"section,omitempty"`
	ComponentName  string                 `protobuf:"bytes,3,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	Type           string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Content        string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Meta           *structpb.Struct       `protobuf:"bytes,6,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_coordinator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{10}
}

func (x *Event) GetWorkerStreamId() int64 {
	if x != nil {
		return x.WorkerStreamId
	}
	return 0
}

func (x *Event) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *Event) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Event) GetMeta() *structpb.Struct {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ListWorkersResponse_Worker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	LastHeartbeat *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersResponse_Worker) Reset() {
	*x = ListWorkersResponse_Worker{}
	mi := &file_coordinator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersResponse_Worker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersResponse_Worker) ProtoMessage() {}

func (x *ListWorkersResponse_Worker) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersResponse_Worker.ProtoReflect.Descriptor instead.
func (*ListWorkersResponse_Worker) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ListWorkersResponse_Worker) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListWorkersResponse_Worker) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ListWorkersResponse_Worker) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListWorkersResponse_Worker) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

var File_coordinator_proto protoreflect.FileDescriptor

const file_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x11coordinator.proto\x12\vprotorender\x1a\fcommon.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x17validate/validate.proto\";\n" +
	"\x15RegisterWorkerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\")\n" +
	"\x17DeregisterWorkerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"~\n" +
	"\x19WorkerStreamStatusRequest\x12(\n" +
	"\x10worker_stream_id\x18\x01 \x01(\x03R\x0eworkerStreamId\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.protorender.WorkerStreamStatusR\x06status\"P\n" +
	"\x1cListComponentConfigsResponse\x120\n" +
	"\x04data\x18\x01 \x03(\v2\x1c.protorender.ComponentConfigR\x04data\"4\n" +
	"\x19GetComponentConfigRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\"J\n" +
	"\x12ListWorkersRequest\x124\n" +
	"\x06status\x18\x01 \x01(\tB\x1c\xfaB\x19r\x17R\x06activeR\binactiveR\x03allR\x06status\"\xe2\x01\n" +
	"\x13ListWorkersResponse\x12;\n" +
	"\x04data\x18\x01 \x03(\v2'.protorender.ListWorkersResponse.WorkerR\x04data\x1a\x8d\x01\n" +
	"\x06Worker\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12A\n" +
	"\x0elast_heartbeat\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\"[\n" +
	"\x12ListStreamsRequest\x12E\n" +
	"\x06status\x18\x01 \x01(\tB-\xfaB*r(R\x06activeR\tcompletedR\x06pausedR\x06failedR\x03allR\x06status\">\n" +
	"\x13ListStreamsResponse\x12'\n" +
	"\x04data\x18\x01 \x03(\v2\x13.protorender.StreamR\x04data\"+\n" +
	"\x10GetStreamRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\"\xfe\x01\n" +
	"\x05Event\x12(\n" +
	"\x10worker_stream_id\x18\x01 \x01(\x03R\x0eworkerStreamId\x12\x18\n" +
	"\asection\x18\x02 \x01(\tR\asection\x12%\n" +
	"\x0ecomponent_name\x18\x03 \x01(\tR\rcomponentName\x12C\n" +
	"\x04type\x18\x04 \x01(\tB/\xfaB,r*R\aPRODUCER\aCONSUMER\x06DELETER\x05ERRORR\aUNKNOWNR\x04type\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12+\n" +
	"\x04meta\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x04meta2\xbd\n" +
	"\n" +
	"\vCoordinator\x12a\n" +
	"\x18UpdateWorkerStreamStatus\x12&.protorender.WorkerStreamStatusRequest\x1a\x1b.protorender.CommonResponse\"\x00\x12t\n" +
	"\x15CreateComponentConfig\x12\x1c.protorender.ComponentConfig\x1a\x1b.protorender.CommonResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v0/component-configs\x12y\n" +
	"\x15UpdateComponentConfig\x12\x1c.protorender.ComponentConfig\x1a\x1b.protorender.CommonResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\x1a\x1a/v0/component-configs/{id}\x12~\n" +
	"\x12GetComponentConfig\x12&.protorender.GetComponentConfigRequest\x1a\x1c.protorender.ComponentConfig\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v0/component-configs/{id}\x12x\n" +
	"\x14ListComponentConfigs\x12\x16.google.protobuf.Empty\x1a).protorender.ListComponentConfigsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v0/component-configs\x12S\n" +
	"\x0eRegisterWorker\x12\".protorender.RegisterWorkerRequest\x1a\x1b.protorender.CommonResponse\"\x00\x12W\n" +
	"\x10DeregisterWorker\x12$.protorender.DeregisterWorkerRequest\x1a\x1b.protorender.CommonResponse\"\x00\x12n\n" +
	"\vListWorkers\x12\x1f.protorender.ListWorkersRequest\x1a .protorender.ListWorkersResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v0/workers/{status}\x12n\n" +
	"\vListStreams\x12\x1f.protorender.ListStreamsRequest\x1a .protorender.ListStreamsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v0/streams/{status}\x12Y\n" +
	"\tGetStream\x12\x1d.protorender.GetStreamRequest\x1a\x13.protorender.Stream\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v0/streams/{id}\x12X\n" +
	"\fCreateStream\x12\x13.protorender.Stream\x1a\x1b.protorender.CommonResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v0/streams\x12]\n" +
	"\fUpdateStream\x12\x13.protorender.Stream\x1a\x1b.protorender.CommonResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10/v0/streams/{id}\x12>\n" +
	"\fIngestEvents\x12\x12.protorender.Event\x1a\x16.google.protobuf.Empty(\x010\x01B4Z2github.com/sananguliyev/airtruct/internal/protogenb\x06proto3"

var (
	file_coordinator_proto_rawDescOnce sync.Once
	file_coordinator_proto_rawDescData []byte
)

func file_coordinator_proto_rawDescGZIP() []byte {
	file_coordinator_proto_rawDescOnce.Do(func() {
		file_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coordinator_proto_rawDesc), len(file_coordinator_proto_rawDesc)))
	})
	return file_coordinator_proto_rawDescData
}

var file_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_coordinator_proto_goTypes = []any{
	(*RegisterWorkerRequest)(nil),        // 0: protorender.RegisterWorkerRequest
	(*DeregisterWorkerRequest)(nil),      // 1: protorender.DeregisterWorkerRequest
	(*WorkerStreamStatusRequest)(nil),    // 2: protorender.WorkerStreamStatusRequest
	(*ListComponentConfigsResponse)(nil), // 3: protorender.ListComponentConfigsResponse
	(*GetComponentConfigRequest)(nil),    // 4: protorender.GetComponentConfigRequest
	(*ListWorkersRequest)(nil),           // 5: protorender.ListWorkersRequest
	(*ListWorkersResponse)(nil),          // 6: protorender.ListWorkersResponse
	(*ListStreamsRequest)(nil),           // 7: protorender.ListStreamsRequest
	(*ListStreamsResponse)(nil),          // 8: protorender.ListStreamsResponse
	(*GetStreamRequest)(nil),             // 9: protorender.GetStreamRequest
	(*Event)(nil),                        // 10: protorender.Event
	(*ListWorkersResponse_Worker)(nil),   // 11: protorender.ListWorkersResponse.Worker
	(WorkerStreamStatus)(0),              // 12: protorender.WorkerStreamStatus
	(*ComponentConfig)(nil),              // 13: protorender.ComponentConfig
	(*Stream)(nil),                       // 14: protorender.Stream
	(*structpb.Struct)(nil),              // 15: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),        // 16: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 17: google.protobuf.Empty
	(*CommonResponse)(nil),               // 18: protorender.CommonResponse
}
var file_coordinator_proto_depIdxs = []int32{
	12, // 0: protorender.WorkerStreamStatusRequest.status:type_name -> protorender.WorkerStreamStatus
	13, // 1: protorender.ListComponentConfigsResponse.data:type_name -> protorender.ComponentConfig
	11, // 2: protorender.ListWorkersResponse.data:type_name -> protorender.ListWorkersResponse.Worker
	14, // 3: protorender.ListStreamsResponse.data:type_name -> protorender.Stream
	15, // 4: protorender.Event.meta:type_name -> google.protobuf.Struct
	16, // 5: protorender.ListWorkersResponse.Worker.last_heartbeat:type_name -> google.protobuf.Timestamp
	2,  // 6: protorender.Coordinator.UpdateWorkerStreamStatus:input_type -> protorender.WorkerStreamStatusRequest
	13, // 7: protorender.Coordinator.CreateComponentConfig:input_type -> protorender.ComponentConfig
	13, // 8: protorender.Coordinator.UpdateComponentConfig:input_type -> protorender.ComponentConfig
	4,  // 9: protorender.Coordinator.GetComponentConfig:input_type -> protorender.GetComponentConfigRequest
	17, // 10: protorender.Coordinator.ListComponentConfigs:input_type -> google.protobuf.Empty
	0,  // 11: protorender.Coordinator.RegisterWorker:input_type -> protorender.RegisterWorkerRequest
	1,  // 12: protorender.Coordinator.DeregisterWorker:input_type -> protorender.DeregisterWorkerRequest
	5,  // 13: protorender.Coordinator.ListWorkers:input_type -> protorender.ListWorkersRequest
	7,  // 14: protorender.Coordinator.ListStreams:input_type -> protorender.ListStreamsRequest
	9,  // 15: protorender.Coordinator.GetStream:input_type -> protorender.GetStreamRequest
	14, // 16: protorender.Coordinator.CreateStream:input_type -> protorender.Stream
	14, // 17: protorender.Coordinator.UpdateStream:input_type -> protorender.Stream
	10, // 18: protorender.Coordinator.IngestEvents:input_type -> protorender.Event
	18, // 19: protorender.Coordinator.UpdateWorkerStreamStatus:output_type -> protorender.CommonResponse
	18, // 20: protorender.Coordinator.CreateComponentConfig:output_type -> protorender.CommonResponse
	18, // 21: protorender.Coordinator.UpdateComponentConfig:output_type -> protorender.CommonResponse
	13, // 22: protorender.Coordinator.GetComponentConfig:output_type -> protorender.ComponentConfig
	3,  // 23: protorender.Coordinator.ListComponentConfigs:output_type -> protorender.ListComponentConfigsResponse
	18, // 24: protorender.Coordinator.RegisterWorker:output_type -> protorender.CommonResponse
	18, // 25: protorender.Coordinator.DeregisterWorker:output_type -> protorender.CommonResponse
	6,  // 26: protorender.Coordinator.ListWorkers:output_type -> protorender.ListWorkersResponse
	8,  // 27: protorender.Coordinator.ListStreams:output_type -> protorender.ListStreamsResponse
	14, // 28: protorender.Coordinator.GetStream:output_type -> protorender.Stream
	18, // 29: protorender.Coordinator.CreateStream:output_type -> protorender.CommonResponse
	18, // 30: protorender.Coordinator.UpdateStream:output_type -> protorender.CommonResponse
	17, // 31: protorender.Coordinator.IngestEvents:output_type -> google.protobuf.Empty
	19, // [19:32] is the sub-list for method output_type
	6,  // [6:19] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_coordinator_proto_init() }
func file_coordinator_proto_init() {
	if File_coordinator_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coordinator_proto_rawDesc), len(file_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coordinator_proto_goTypes,
		DependencyIndexes: file_coordinator_proto_depIdxs,
		MessageInfos:      file_coordinator_proto_msgTypes,
	}.Build()
	File_coordinator_proto = out.File
	file_coordinator_proto_goTypes = nil
	file_coordinator_proto_depIdxs = nil
}
