// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: worker.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlowFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowFile) Reset() {
	*x = FlowFile{}
	mi := &file_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowFile) ProtoMessage() {}

func (x *FlowFile) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowFile.ProtoReflect.Descriptor instead.
func (*FlowFile) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

func (x *FlowFile) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FlowFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type AssignFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerFlowId  int64                  `protobuf:"varint,1,opt,name=worker_flow_id,json=workerFlowId,proto3" json:"worker_flow_id,omitempty"`
	Config        string                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Files         []*FlowFile            `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignFlowRequest) Reset() {
	*x = AssignFlowRequest{}
	mi := &file_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignFlowRequest) ProtoMessage() {}

func (x *AssignFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignFlowRequest.ProtoReflect.Descriptor instead.
func (*AssignFlowRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

func (x *AssignFlowRequest) GetWorkerFlowId() int64 {
	if x != nil {
		return x.WorkerFlowId
	}
	return 0
}

func (x *AssignFlowRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *AssignFlowRequest) GetFiles() []*FlowFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type FetchFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerFlowId  int64                  `protobuf:"varint,1,opt,name=worker_flow_id,json=workerFlowId,proto3" json:"worker_flow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchFlowRequest) Reset() {
	*x = FetchFlowRequest{}
	mi := &file_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchFlowRequest) ProtoMessage() {}

func (x *FetchFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchFlowRequest.ProtoReflect.Descriptor instead.
func (*FetchFlowRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{2}
}

func (x *FetchFlowRequest) GetWorkerFlowId() int64 {
	if x != nil {
		return x.WorkerFlowId
	}
	return 0
}

type FetchFlowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        WorkerFlowStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=protorender.WorkerFlowStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchFlowResponse) Reset() {
	*x = FetchFlowResponse{}
	mi := &file_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchFlowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchFlowResponse) ProtoMessage() {}

func (x *FetchFlowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchFlowResponse.ProtoReflect.Descriptor instead.
func (*FetchFlowResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{3}
}

func (x *FetchFlowResponse) GetStatus() WorkerFlowStatus {
	if x != nil {
		return x.Status
	}
	return WorkerFlowStatus_waiting
}

type CompleteFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerFlowId  int64                  `protobuf:"varint,1,opt,name=worker_flow_id,json=workerFlowId,proto3" json:"worker_flow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteFlowRequest) Reset() {
	*x = CompleteFlowRequest{}
	mi := &file_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteFlowRequest) ProtoMessage() {}

func (x *CompleteFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteFlowRequest.ProtoReflect.Descriptor instead.
func (*CompleteFlowRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteFlowRequest) GetWorkerFlowId() int64 {
	if x != nil {
		return x.WorkerFlowId
	}
	return 0
}

type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerFlowId  int64                  `protobuf:"varint,1,opt,name=worker_flow_id,json=workerFlowId,proto3" json:"worker_flow_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{5}
}

func (x *IngestRequest) GetWorkerFlowId() int64 {
	if x != nil {
		return x.WorkerFlowId
	}
	return 0
}

func (x *IngestRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *IngestRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *IngestRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *IngestRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Response      []byte                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{6}
}

func (x *IngestResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *IngestResponse) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_worker_proto protoreflect.FileDescriptor

const file_worker_proto_rawDesc = "" +
	"\n" +
	"\fworker.proto\x12\vprotorender\x1a\x1bgoogle/protobuf/empty.proto\x1a\fcommon.proto\"6\n" +
	"\bFlowFile\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"~\n" +
	"\x11AssignFlowRequest\x12$\n" +
	"\x0eworker_flow_id\x18\x01 \x01(\x03R\fworkerFlowId\x12\x16\n" +
	"\x06config\x18\x02 \x01(\tR\x06config\x12+\n" +
	"\x05files\x18\x03 \x03(\v2\x15.protorender.FlowFileR\x05files\"8\n" +
	"\x10FetchFlowRequest\x12$\n" +
	"\x0eworker_flow_id\x18\x01 \x01(\x03R\fworkerFlowId\"J\n" +
	"\x11FetchFlowResponse\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.protorender.WorkerFlowStatusR\x06status\";\n" +
	"\x13CompleteFlowRequest\x12$\n" +
	"\x0eworker_flow_id\x18\x01 \x01(\x03R\fworkerFlowId\"\x9e\x01\n" +
	"\rIngestRequest\x12$\n" +
	"\x0eworker_flow_id\x18\x01 \x01(\x03R\fworkerFlowId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"L\n" +
	"\x0eIngestResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\fR\bresponse2\xff\x02\n" +
	"\x06Worker\x12D\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a\x1b.protorender.CommonResponse\"\x00\x12K\n" +
	"\n" +
	"AssignFlow\x12\x1e.protorender.AssignFlowRequest\x1a\x1b.protorender.CommonResponse\"\x00\x12L\n" +
	"\tFetchFlow\x12\x1d.protorender.FetchFlowRequest\x1a\x1e.protorender.FetchFlowResponse\"\x00\x12O\n" +
	"\fCompleteFlow\x12 .protorender.CompleteFlowRequest\x1a\x1b.protorender.CommonResponse\"\x00\x12C\n" +
	"\x06Ingest\x12\x1a.protorender.IngestRequest\x1a\x1b.protorender.IngestResponse\"\x00B4Z2github.com/sananguliyev/airtruct/internal/protogenb\x06proto3"

var (
	file_worker_proto_rawDescOnce sync.Once
	file_worker_proto_rawDescData []byte
)

func file_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)))
	})
	return file_worker_proto_rawDescData
}

var file_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_worker_proto_goTypes = []any{
	(*FlowFile)(nil),            // 0: protorender.FlowFile
	(*AssignFlowRequest)(nil),   // 1: protorender.AssignFlowRequest
	(*FetchFlowRequest)(nil),    // 2: protorender.FetchFlowRequest
	(*FetchFlowResponse)(nil),   // 3: protorender.FetchFlowResponse
	(*CompleteFlowRequest)(nil), // 4: protorender.CompleteFlowRequest
	(*IngestRequest)(nil),       // 5: protorender.IngestRequest
	(*IngestResponse)(nil),      // 6: protorender.IngestResponse
	(WorkerFlowStatus)(0),       // 7: protorender.WorkerFlowStatus
	(*emptypb.Empty)(nil),       // 8: google.protobuf.Empty
	(*CommonResponse)(nil),      // 9: protorender.CommonResponse
}
var file_worker_proto_depIdxs = []int32{
	0, // 0: protorender.AssignFlowRequest.files:type_name -> protorender.FlowFile
	7, // 1: protorender.FetchFlowResponse.status:type_name -> protorender.WorkerFlowStatus
	8, // 2: protorender.Worker.HealthCheck:input_type -> google.protobuf.Empty
	1, // 3: protorender.Worker.AssignFlow:input_type -> protorender.AssignFlowRequest
	2, // 4: protorender.Worker.FetchFlow:input_type -> protorender.FetchFlowRequest
	4, // 5: protorender.Worker.CompleteFlow:input_type -> protorender.CompleteFlowRequest
	5, // 6: protorender.Worker.Ingest:input_type -> protorender.IngestRequest
	9, // 7: protorender.Worker.HealthCheck:output_type -> protorender.CommonResponse
	9, // 8: protorender.Worker.AssignFlow:output_type -> protorender.CommonResponse
	3, // 9: protorender.Worker.FetchFlow:output_type -> protorender.FetchFlowResponse
	9, // 10: protorender.Worker.CompleteFlow:output_type -> protorender.CommonResponse
	6, // 11: protorender.Worker.Ingest:output_type -> protorender.IngestResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_worker_proto_init() }
func file_worker_proto_init() {
	if File_worker_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_depIdxs,
		MessageInfos:      file_worker_proto_msgTypes,
	}.Build()
	File_worker_proto = out.File
	file_worker_proto_goTypes = nil
	file_worker_proto_depIdxs = nil
}
